spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: testsimply
  jackson:
    time-zone: GMT+8
  #    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
      bindings:
        request-enum:
          destination: request.enum
          binder: rabbit
          group: ${spring.application.name}
        receive-enum:
          destination: receive.enum
          binder: rabbit
  rabbitmq:
    host: 192.168.0.40
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
    sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 0.5
  cache:
    type: redis
    #mongoDb:存mongoDb ; dataBase: 存数据库
    fileStorageType: mongoDb
feign:
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  ServerListRefreshInterval: 5000 # ribbon拉取服务时间间隔
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      displayName: mybatis-example
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.210.129:2001/eureka/ #SZF
server:
  max-http-header-size: 256KB
rongji:
  module:
    limit-max: 6000
---
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true
  solr:
    DefaultCollection: Microservices
    ZkHost: 192.168.210.134:2166
    ZkClientTimeout: 15000
    ZkConnectTimeout: 50000
  datasource:
    # 特定连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.oscar.Driver
    url: jdbc:oscar://192.168.210.134:2003/OSRDB
    username: FJSZF
    password: FJSZF
#    max-pool-size: 14
    aliases: szf  #数据源别名，使用空格或半角逗号分隔
#  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
#  datasource-multi-enable: true
  datasource-multi:
    sft:
      driver-class-name: dm.jdbc.driver.DmDriver
      url: jdbc:dm://192.168.210.77:5236
      username: SFTOA
      password: "123456789"
#      max-pool-size: 14
    test:
      # 默认 hikari
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.210.153:3399/xc_demo?connectTimeout=3000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: rjsoft
      password: abcd1234
  rabbitmq:
    host: 192.168.0.40
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.0.40
    database: 10
    port: 6379
eureka:
  instance:
    metadata-map:
      appProvider: true
      #      private: true
#      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
#      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.0.47:2001/eureka/
logging:
  level:
    com.rongji.egov: debug
server:
  port: 6688

---
spring:
  profiles: cloud
  main:
    allow-bean-definition-overriding: true
  solr:
    DefaultCollection: Microservices
    ZkHost: 192.168.210.134:2166
    ZkClientTimeout: 15000
    ZkConnectTimeout: 50000

  #  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: true
  datasource-multi-default-holder: ROOT
#  datasource:
#    # 特定连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.oscar.Driver
#    url: jdbc:oscar://192.168.210.134:2003/OSRDB
#    username: FJSZF
#    password: FJSZF
#    #    max-pool-size: 14
#    aliases: szf  #数据源别名，使用空格或半角逗号分隔
#  datasource-multi:
#    sft:
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://192.168.210.77:5236
#      username: SFTOA
#      password: "123456789"
#    #      max-pool-size: 14
#    test:
#      # 默认 hikari
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.210.153:3399/xc_demo?connectTimeout=3000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      username: rjsoft
#      password: abcd1234
  rabbitmq:
    host: 192.168.0.40
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.0.40
    database: 10
    port: 6379
eureka:
  instance:
    metadata-map:
      appProvider: true
      #      private: true
      #      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
      #      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.0.47:2001/eureka/
mybatis:
  configuration:
    database-id: shentong
logging:
  level:
    com.rongji.egov: debug
server:
  port: 6688


