spring:
  profiles:
    active: dev
  application:
    name: testsimply
  config:
    location: http://192.168.0.42/zhuanglw/config/raw/master/rjegov80/test.sec
server:
    port: 6688
---
spring:
  profiles: dev
  #  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: false
#  datasource-multi-default-holder: ROOT
#eureka:
#  instance:
#    metadata-map:
#      appProvider: true
#      #      private: true
#      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
#      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
logging:
  level:
    com.rongji.egov: debug
---
spring:
  profiles: cloud
  #  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: true
---
spring:
  profiles: migration_rms_resource
  #  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: false
  datasource:
    aliases: default, ROOT, XCOA
    driver-class-name: com.kingbase8.Driver
    url: jdbc:kingbase8://192.168.210.80:54321/EGOV
    username: RJEGOV
    password: "123456789"
  datasource-multi:
    TZBOA:
      driver-class-name: com.kingbase8.Driver
      url: jdbc:kingbase8://192.168.210.80:54321/EGOV
      username: TZBOA
      password: "123456789"
    FJSNYNCT:
      aliases: NPSWB
      driver-class-name: dm.jdbc.driver.DmDriver
      url: jdbc:dm://192.168.210.77:5236
      username: SFTOA
      password: "123456789"
    NPSOA:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.210.153:3399/xc_demo?connectTimeout=3000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: rjsoft
      password: abcd1234
    SFTOA:
      driver-class-name: com.oscar.Driver
      url: jdbc:oscar://192.168.210.134:2003/OSRDB
      username: FJSZF
      password: FJSZF
#  datasource-multi-default-holder: ROOT
#eureka:
#  instance:
#    metadata-map:
#      appProvider: true
#      #      private: true
#      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
#      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
logging:
  level:
    com.rongji.egov: debug
server:
  port: 6688

