spring:
  profiles:
    active: default
  config:
    location: http://192.168.0.42/zhuanglw/env-resources/raw/master/env-resources/src/main/resources/test/application.sec
  application:
    name: testsimply
server:
  port: 6644
---
spring:
  profiles: dev
#  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: false
#  datasource-multi-default-holder: ROOT
#eureka:
#  instance:
#    metadata-map:
#      appProvider: true
#      #      private: true
#      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
#      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
logging:
  level:
    com.rongji.egov: debug
server:
  port: 6688

